name: 'Release'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Set up version variable
      run: |
        VERSION=v$(grep 'versionName ' app/build.gradle | awk '{print $2}' | sed 's|\"||g; s|\r$||g')
        FILENAME=delta-$VERSION
        echo "FILENAME=$FILENAME" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create changelog
      run: |
        mkdir -v changelog && cd $_
        cat << EOF > whatsnew-en-US
        $(grep '^ *<item>' ../app/src/main/res/values/changelog.xml | sed -r 's|<[^>]*>(]]>)?||g; s|^ *|- |g')
        EOF

    - name: Restore the license key
      run: echo LICENSE_KEY="${{ secrets.LICENSE_KEY }}" > local.properties

    - name: Restore the service account
      run: echo "${{ secrets.SERVICE_ACCOUNT_BASE64 }}" | base64 -d > service_account.json

    - name: Build AAB
      run: bash gradlew bundleRelease

    - name: Build APK
      run: bash gradlew assembleRelease

    - name: Move AAB and APK
      run: |
        mkdir -v build && cd $_
        mv -v ../app/build/outputs/bundle/release/*.aab delta.aab
        mv -v ../app/build/outputs/apk/release/*.apk delta.apk

    - name: Sign AAB and APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: build
        signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
        alias: ${{ secrets.KEYSTORE_KEY_ALIAS }}

    - name: Rename AAB and APK
      run: |
        mv -v build/*.aab ${{ env.FILENAME }}.aab
        mv -v build/*.apk ${{ env.FILENAME }}.apk

    - name: Upload APK in Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.FILENAME }}
        path: ${{ env.FILENAME }}.apk
        retention-days: 30

    - name: Create a GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.FILENAME }}.apk
        name: ${{ env.VERSION }}
        tag_name: ${{ env.VERSION }}
        body_path: changelog/whatsnew-en-US

    - name: Publish a release to Google Play
      uses: r0adkll/upload-google-play@v1.0.15
      with:
        track: production
        releaseFiles: ${{ env.FILENAME }}.aab
        serviceAccountJson: service_account.json
        packageName: website.leifs.delta
        mappingFile: app/build/outputs/mapping/release/mapping.txt
        whatsNewDirectory: changelog
        inAppUpdatePriority: 5
